import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";
import SessionWrapper from "@/components/layout/SessionWrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Hivve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased `}>
        <SessionWrapper>
          <ToastContainer autoClose={2000} hideProgressBar={true} transition={Slide} theme="dark" />
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
